name: Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build & push image
      run: |
        docker build -t ghcr.io/remichenouri/ubisoft_people_analytics:latest .
        docker push ghcr.io/remichenouri/ubisoft_people_analytics:latest

    - name: Deploy Streamlit Cloud
      uses: palantir/actions-streamlit@v1
      with:
        token: ${{ secrets.STREAMLIT_TOKEN }}
        appName: ubisoft_people_analytics
